name: Build on change to src

on:
    push:
        branches:
            - main
    #paths:
    #  - "src/**"
    #  - "static/**"
    #  - "svelte.config.js"
    # Allow this to be called from other workflows
    workflow_call:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

# The following is from SvelteKit recommendation https://kit.svelte.dev/docs/adapter-static
jobs:
    build_site:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm install

            - name: build
              env:
                  BASE_PATH: "/${{ github.event.repository.name }}"
              run: |
                  npm run build

            - name: Upload Artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  # this should match the `pages` option in your adapter-static options
                  path: "build/"

    deploy:
        needs: build_site
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
